//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracriceMiniProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTrain()
        {
            this.tblBookings = new HashSet<tblBooking>();
            this.tblCancellations = new HashSet<tblCancellation>();
            this.tblClassDetails = new HashSet<tblClassDetail>();
        }
    
        public int Train_No { get; set; }
        public string Train_Name { get; set; }
        public string Source_Station { get; set; }
        public string Destination_Station { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBooking> tblBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCancellation> tblCancellations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClassDetail> tblClassDetails { get; set; }
    }
}
